### PR TITLE
Develop: integrating deadbolt for authorization management

### PR DESCRIPTION
**Pull request by cdparra**
Following issue #57, this request ntegrates deadbolt for authorization management. 
No tests are available right now, but the annotation for controlling that an user is present via deadbolt is in use in the endpoint /assemblies, can be demoed. Code to be reviewed is in the security package. 
Next steps: 
* Implement MyDynamicResourceHandler to control access of groups and assemblies
* Modify routes so that the id of the group or assembly is in the path for contributions and configs 

Please, proceed to close issue #57 too

### CODE REVIEW

**Comment by animeshpathak** [comment]
Hi, 
How exactly can I verify this? It will help if you can list a series of steps which should work if this issue is resolved [log in, do x, do y, expect z].
Thanks.

**Comment by cdparra** [comment]
1. Install the platform on your local computer (follow the readme in the root) 
2. Run it
3. Try to access http://localhost:9000/assemblies (the only endpoint secured with deadbolt so far)
4. Not being logged in, you should received the following message:

```json
{
responseStatus: "UNAUTHORIZED",
statusMessage: "Authentication failed",
errorTrace: null,
newResourceId: null,
newResourceURL: null
} 
```

**Comment by cdparra** [comment]
Option 2: 

Skipe 1 and 2 and try 3 with the following URL: https://appcivist-pb.herokuapp.com/api/assemblies

The current version is deployed there.

**Comment by cdparra** [comment]
Hi Animesh, I will proceed with merge request to move to the other issues in the queue. Since we don't have a big team yet, I would prefer just to move quickly and merge the pull requests asap on my own, at least until we have the alpha

**Pull request merged**
